### ISSUE TITLE
Error when running with sitespeed

### ISSUE THREAD

**Issue by jdmchone** [sitespeedio/plugin-gpsi#21]
Issue:
So, when I upgraded to 12.3.1, and installed both the gpsi and lighthouse plugin, the gpsi plugin started to break. I thought it was lighthouse that was breaking at first, but discovered that gpsi runs lighthouse, then it runs again after the test is done. Here is one of the error messages:

start.sh -n1 https://www.google.com
Google Chrome 80.0.3987.149 
Mozilla Firefox 72.0
[2020-03-31 00:22:09] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.16.1 sitespeed.io: 12.3.1 browsertime: 8.3.1 coach: 5.0.1
[2020-03-31 00:22:10] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-03-31 00:22:10] INFO: Sending url https://www.google.com to test on Page Speed Insights
[2020-03-31 00:22:10] INFO: Running tests using Chrome - 1 iteration(s)
[2020-03-31 00:22:12] INFO: Testing url https://www.google.com iteration 1
[2020-03-31 00:22:14] ERROR: Error: Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 429)
    at Gaxios.<anonymous> (/node_modules/gaxios/build/src/gaxios.js:73:27)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I know it says status code 429. That's what I get when running against google.com (there are no network issues, btw. I can curl it just fine.) Other times, when I run again other sites, the status it's a client error. This has happened since updating from 12.2.0 to 12.3.1.

**Comment by jdmchone** [comment]
If I turn OFF the gpsi plugin, it works fine, and so does lighthouse:
/start.sh -n1 https://www.google.com
Google Chrome 80.0.3987.149 
Mozilla Firefox 72.0
[2020-03-31 00:37:58] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.16.1 sitespeed.io: 12.3.1 browsertime: 8.3.1 coach: 5.0.1
[2020-03-31 00:37:58] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-03-31 00:37:58] INFO: Running tests using Chrome - 1 iteration(s)
[2020-03-31 00:37:59] INFO: Testing url https://www.google.com iteration 1
[2020-03-31 00:38:13] INFO: https://www.google.com 23 requests, backEndTime: 191ms, firstPaint: 320ms, firstVisualChange: 366ms, DOMContentLoaded: 370ms, Load: 969ms, speedIndex: 599, perceptualSpeedIndex: 462, visualComplete85: 900ms, lastVisualChange: 6.37s, rumSpeedIndex: 322
[2020-03-31 00:38:13] INFO: Start collecting Lighthouse result for https://www.google.com iteration 1
[2020-03-31 00:38:21] INFO: HTML stored in /gpsi/sitespeed-result/www.google.com/2020-03-31-00-37-58

**Comment by soulgalore** [comment]
Hi @jdmchone I've seen the same both on the GSPI plugin and  https://developers.google.com/speed/pagespeed/insights/ 

<img width="698" alt="Screen Shot 2020-03-31 at 1 45 09 PM" src="https://user-images.githubusercontent.com/540757/78022799-dd462e80-7355-11ea-9dc5-ba2c0697e5e9.png">

So Google has throttled or just don't want us to test Google.com is my guess. I also wanted to test google.com to more easily get the CruX data and compare it to other sites.

In 12.2.0 we switched to the "new" GPSI backend that used Lighthouse, before that we used the old version.

**Comment by soulgalore** [comment]
Also see https://twitter.com/soulislove/status/1243084454601666563 and it seems to work sometimes.

**Comment by jdmchone** [comment]
It's not just google. It's any site I try to hit. Previous sites that I was checking worked fine, and now they no longer work with gpsi.

**Comment by soulgalore** [comment]
Do they work when you test on https://developers.google.com/speed/pagespeed/insights/ or could it be a gpsi.key thing?

**Comment by jdmchone** [comment]
Maybe. Not actually creating my own key. In the past, I just did this to install gpsi in my container:

git clone https://github.com/sitespeedio/plugin-gpsi.git .
npm install --production

When I created my last container, which contains sitespeed.io 12.2.0, it worked fine. But, when I try to build with 12.3.1, and do the same gpsi install, gpsi fails when running.

ERROR: Error: Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_BLOCKED_BY_CLIENT)
    at Gaxios.<anonymous> (/gpsi/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/gpsi/node_modules/gaxios/build/src/gaxios.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jdmchone** [comment]
I can understand the google 429 issue, but what's with Details: net::ERR_BLOCKED_BY_CLIENT? Is that a gpsi key issue?

**Comment by soulgalore** [comment]
No I'm pretty sure 12.2.0 uses the new backend, really strange? If you look at the HTML output, there's a difference between the old and the new, can you check?

**Comment by jdmchone** [comment]
I'll check. In the meantime, what key is being used for gpsi if I don't specify a key?

**Comment by soulgalore** [comment]
Then you run without a key.

**Comment by jdmchone** [comment]
When I pulled down the 12.2.0 version, I didn't also pull down the latest gpsi plugin.

**Comment by jdmchone** [comment]
It's really weird. The lighthouse plugin by itself works fine:

```
# echo $SITESPEED_IO_PLUGINS__ADD
/lighthouse
# sitespeed.io -n1 https://www.google.com
INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.16.1 sitespeed.io: 12.3.1 browsertime: 8.3.1 coach: 5.0.1
INFO: Will run Lighthouse tests after Browsertime has finished
INFO: Running tests using Chrome - 1 iteration(s)
INFO: Testing url https://www.google.com iteration 1
INFO: https://www.google.com 22 requests, backEndTime: 205ms, firstPaint: 354ms, firstVisualChange: 387ms, DOMContentLoaded: 407ms, Load: 1.11s, speedIndex: 512, perceptualSpeedIndex: 406, visualComplete85: 452ms, lastVisualChange: 6.65s, rumSpeedIndex: 355
INFO: Start collecting Lighthouse result for https://www.google.com iteration 1
INFO: HTML stored in /sitespeed.io/sitespeed-result/www.google.com/2020-04-03-14-11-36
```
but when gpsi tries to run it, it fails:

```
# echo $SITESPEED_IO_PLUGINS__ADD
/lighthouse,/gpsi
# sitespeed.io -n1 https://www.google.com
INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.16.1 sitespeed.io: 12.3.1 browsertime: 8.3.1 coach: 5.0.1
INFO: Will run Lighthouse tests after Browsertime has finished
INFO: Sending url https://www.google.com to test on Page Speed Insights
INFO: Running tests using Chrome - 1 iteration(s)
INFO: Testing url https://www.google.com iteration 1
ERROR: Error: Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 429)
    at Gaxios.<anonymous> (/gpsi/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/gpsi/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
INFO: https://www.google.com 25 requests, backEndTime: 238ms, firstPaint: 405ms, firstVisualChange: 433ms, DOMContentLoaded: 439ms, Load: 1.12s, speedIndex: 531, perceptualSpeedIndex: 461, visualComplete85: 466ms, lastVisualChange: 6.57s, rumSpeedIndex: 406
INFO: Start collecting Lighthouse result for https://www.google.com iteration 1
INFO: HTML stored in /sitespeed.io/sitespeed-result/www.google.com/2020-04-03-14-14-59
```

**Comment by jdmchone** [comment]
So, can GPSI not use my IP, so it doesn't break?

**Comment by soulgalore** [comment]
> regular site still breaks in updated GPSI.

GPSI uses Googles servers to do the call, could it be that your server or your CDN has something implemented that gives the 429? Created an upstream issue at https://github.com/GoogleChromeLabs/psi with the URL you use and maybe they can help you?

**Comment by soulgalore** [comment]
Closing since its something going on at Google.
