### ISSUE TITLE
Catch missing metrics

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/plugin-gpsi#42]
There's a case on our test server where we don't get data for CLS:
```
[2021-09-09 09:00:29] INFO: Got https://www.sitespeed.io/ analysed from Google Page Speed Insights
[2021-09-09 09:00:29] ERROR: TypeError: Cannot read property 'percentile' of undefined
    at Object.repackage (/gpsi/lib/pageSummary.js:68:70)
    at /gpsi/lib/index.js:93:50
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by MasterGordon** [comment]
Any news on this issue, also recieving the same issune:
```
ERROR: TypeError: Cannot read properties of undefined (reading 'percentile')
    at repackageSummary (file:///gpsi/lib/summary.js:22:14)
    at file:///gpsi/lib/index.js:103:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Running the latest version (27.3.1-plus1) inside docker

**Comment by soulgalore** [comment]
I guess we need to make a check for all metrics. In your case I could see that the site you are testing is missing First input delay metrics.

**Comment by soulgalore** [comment]
Going out in the next release.
