### ISSUE TITLE
GPSI returns quota errors when called with too many URLs

### ISSUE THREAD

**Issue by shiftie** [sitespeedio/plugin-gpsi#7]
Hi, firstly, thx for this implementation!

When docker -plus1 image is ran with a lot of URLs (>10), those URLs are passed to GPSI at the same time, leading to an error response from GPSI.

Each URL should be processed sequentially or the stack of parallel requests should be limited to not go above GPSI limits.

ps.: i've tried with `--gpsi.key  myAPIkey` added as parameter

```
INFO: [browsertime] Running tests using Chrome - 1 iteration(s)
ERROR: [sitespeedio.queuehandler] Error: Unable to process request. Please wait a while and try again.
at createError (/gpsi/node_modules/axios/lib/core/createError.js:16:15)
at settle (/gpsi/node_modules/axios/lib/core/settle.js:18:12)
at Unzip.handleStreamEnd (/gpsi/node_modules/axios/lib/adapters/http.js:201:11)
at Unzip.emit (events.js:187:15)
at Unzip.EventEmitter.emit (domain.js:442:20)
at endReadableNT (_stream_readable.js:1094:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
(node:18) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
at JSON.stringify (<anonymous>)
at queue.processingEnded.obj (/usr/src/app/lib/core/queueHandler.js:148:61)
at eventuateConsume (/usr/src/app/node_modules/eventuate/index.js:31:13)
at Array.forEach (<anonymous>)
at Function.eventuate.produce (/usr/src/app/node_modules/eventuate/index.js:30:19)
at Object.onReject [as reject] (/usr/src/app/node_modules/concurrent-queue/index.js:45:36)
at reject (/usr/src/app/node_modules/concurrent-queue/index.js:85:22)
at f (/usr/src/app/node_modules/concurrent-queue/node_modules/once/once.js:17:25)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by AlexBatorykLeliw** [comment]
Is there any updates on this issue? We find that when we run ~20 URLs through the `plus1` image, we get the same response

**Comment by soulgalore** [comment]
Oops, I missed this issue. @shiftie so you mean GPSI has a limit of concurrent request? I would put that on the outside, run one tests, wait, run another. 

@AlexBatorykLeliw and you use a key? Before CRUX was released we used GSPI to get data for https://grafana.wikimedia.org/d/t_bhsNGMk/chrome-user-experience-report?orgId=1 and then we just run them direct after each other and I don't remember we got any errors (but maybe something changed on the GPSI side).

**Comment by AlexBatorykLeliw** [comment]
It seems like there is a hard limit of ~20 URLs which can be run before getting the error below. This can be replicated by specifying the plugin and key.
![image](https://user-images.githubusercontent.com/10847190/100100330-8ea35280-2e58-11eb-8877-202141cf498f.png)

The command I'm using to get this error is:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:15.9.0-plus1 --gpsi.key=${KEY} ./urls.txt`

**Comment by soulgalore** [comment]
Hi @AlexBatorykLeliw I see, I made a PR for running at most 10 tests at the same time I hope that would fix it.

**Comment by AlexBatorykLeliw** [comment]
That looks great. Hopefully this fixes it. Approved 👍

**Comment by shiftie** [comment]
Hi!

I've tested with:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:15.9.0-plus1 --gpsi.key MY_KEY ./urls.txt`
urls.txt has ~30 URLs

This outputs:

```
Google Chrome 87.0.4280.66
Mozilla Firefox 83.0
[2020-12-07 09:32:46] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.16.2 sitespeed.io: 15.9.0 browsertime: 10.9.0 coach: 5.1.1
[2020-12-07 09:32:48] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-12-07 09:32:48] INFO: Sending url <some-url> to test on Page Speed Insights
[2020-12-07 09:32:48] INFO: Sending url <some-other> to test on Page Speed Insights
....
[2020-12-07 09:32:48] INFO: Running tests using Chrome - 3 iteration(s)
[2020-12-07 09:32:48] ERROR: Error: Quota exceeded. Please wait a while and try again.
    at Gaxios.<anonymous> (/gpsi/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/gpsi/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-12-07 09:32:48] ERROR: Error: Quota exceeded. Please wait a while and try again.
    at Gaxios.<anonymous> (/gpsi/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/gpsi/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
....
```

**Comment by AlexBatorykLeliw** [comment]
Version `15.9.0-plus1` of sitespeed.io docker image doesn't look like it has the latest master branch for this plugin, so I would expect this until a new docker image is pushed with the new plugin.

**Comment by soulgalore** [comment]
This was released some time ago.
